from pathlib import Path
from runtime_paths import CORE_DB
import json,hashlib,pandas as pd,duckdb
ROOT=Path(__file__).resolve().parents[3];OUT=ROOT/'paper/revision_v3';E=OUT/'evidence';downloads={x['file']:x for x in json.loads((E/'download_manifest.json').read_text())}
rows=[]
def add(key,file,version,page,assets,fields,support,assumption,impact):
 d=downloads.get(file,{});rows.append(dict(claim_id=key,document=file,document_version=version,pdf_page_or_section=page,source_url=d.get('url',''),sha256=d.get('sha256',''),applicable_assets=assets,fields=fields,source_support=support,engineering_assumption=assumption,impact_scope=impact))
add('APA_TRANCOSO','apa_AIA3403.pdf','July 2021; AIA 3403','PDF 5 (printed 3)','GEN:01017; GEN:01018; EREDES:252337344 export corridor','connection_voltage_kv; route_length_km; destination','60 kV; 11.4 km; Trancoso distribution substation','Matching project corridor to generated bus ID requires GIS/routing inference','Connection-audit variant only; core nearest-bus mapping is retained, not silently corrected')
add('APA_SERNANCELHE','apa_ppa421.html','Snapshot 2026-09-21; PPA 421; AIA 2009','HTML fields Designação do projeto; Fase; Data de início da exploração','GEN:01099; GEN:01100','named_connection; nominal_voltage; commissioning','Sernancelhe to Moimenta 60 kV; constructed; operation date blank','Injection at Moimenta 400 kV collapses unobserved collector/transformer; actual commissioning unknown','Connection-audit variant; PPA is not evidence for a measured 400 kV generator terminal or operation date')
add('APA_MOIMENTA','apa_ppa407.html','Snapshot 2026-09-21; PPA 407; AIA 2009','HTML Designação do projeto; Fase; Data de início da exploração','Douro Sul–Moimenta–Armamar corridor','named_connection; nominal_voltage; commissioning','400 kV project; stale page says under construction; operation date blank','No historical in-service date inferred from this project page','Connectivity context only; not a historical availability input')
add('DGEG_BESS','dgeg_casal_2025.html','Technical visit 18 June 2025; snapshot 2026-09-21','HTML Visita técnica a unidade de armazenamento de Casal da Cortiça','GEN:01189','nameplate_mw; available_from_utc; bus_id','12 MVA; 24 MWh; connected in June 2025','12 MVA→12 MW assumes power factor 1; June 1 is month-start proxy; colocated bus inferred','At most 12 MW allocation location and June 1–17 early availability uncertain; national power is conserved')
add('REE_LIST','ree_interconexiones.pdf','September 2012','PDF 10 (printed 10); date PDF 20','7 model boundary buses / 9 represented circuits','interconnector_name; voltage_kv; circuit_count','Historical named corridors and planned exchange capacities','2012 map does not prove 2025–26 operation, low-voltage coverage or independently validate all 9 circuit identities','Background naming only; 7 model boundaries are a selected 220/400 kV equivalent, not all physical ES–PT links')
add('CONDUCTOR_R','tocha_II_2019.pdf','19 February 2019; process 2800-19C007374; AIA3274','PDF 3,5 (printed 2,4)','PE Tocha II–Tocha 60 kV ACSR 325; transfer to 1,517 model line rows','r_ohm_per_km; r_status','R20=0.1093 ohm/km for ACSR total 326.1 mm2; aluminium 264.4 mm2; steel 61.7 mm2','R=0.1093*325/A/n and length weighting transfer a project value across conductor classes; no AC/operating-temperature correction; n from 2x prefix','All 1,517 CONDUCTOR_DERIVED rows are partial-source engineering transfer, not direct resistance observations; other 3,426 remain engineering proxies')
add('ESTOI_PARALLEL','estoi_pdirt_2015.pdf','REN PDIRT 2016–2025 proposal; file labelled 2015; no stronger cover issue date assumed','Annex 6; PDF 50,52,54,56; printed 8,10,12,14','RARI:Estoi; 150/60 kV aggregate','sn_mva=126; parallel=3; voltage side','3 units ×126 MVA=378 MVA shown for planned end-2016/2018/2020/2025 inventories','Identical parallel units, common bus endpoint and all simultaneously available at each case are operational equivalents, not measured switch states','N−1 corrected variant only; one outage reduces parallel 3→2. Planning horizon is not an actual commissioning date')
add('GEOPANDAS','geopandas_crossref.json','DOI 10.1016/j.compenvurbsys.2026.102495; checked 2026-09-21','Crossref title/author/issued/volume/article-number; official CITATION.md','Software bibliography','author; year; title; DOI','Fleischmann et al.; 2026; volume130 article102495; assigned December 2026 issue','Issue date is not asserted as online publication date','Keep 2026; distinguish used package version in environment lock')
pd.DataFrame(rows).to_csv(OUT/'citation_evidence_ledger.csv',index=False)
# Explicit field-level downgrade overlay; original byte-identical model is not rewritten.
c=duckdb.connect(str(CORE_DB),read_only=True)
r=c.sql("select line_id,r_ohm_per_km,r_status from grid.lines where r_status like 'CONDUCTOR_DERIVED%'").df();r['reviewed_evidence_status']='PROJECT_PARAMETER_TRANSFER_ENGINEERING_ASSUMPTION';r['evidence_key']='CONDUCTOR_R';r.to_csv(OUT/'resistance_evidence_overlay.csv',index=False)
av=[
['E-REDES RND AT','Frozen source hashes; portal vintage retained in raw archive','No complete device validity dates','Source in_service fixed; 60/130 kV geometry','Unknown dates remain static; not a historical switching reconstruction'],
['OSM/Geofabrik','Frozen PBF and derived JSON SHA-256','Extraction snapshot != validity at case date','Source topology fixed for 150/220/400 kV','No blanket date gate for ordinary lines; future/retired records may remain'],
['Transformers / RARI / REN totals','Frozen core + separate corrected N−1 models','No unit-level commissioning histories','228 model rows fixed; Estoi parallel equivalent only in N−1','Unknown actual unit and tap status declared; Estoi 2016–25 planning inventory is not actual operation'],
['Minho–Galicia interconnection','REE announcement 2026-07-02','2026-07-02T00:00Z day-resolution proxy','LINE:009732; LINE:009814 disabled for every case before 2026-03-24','Explicit date gate; no inferred pre-commission operation'],
['Other ES–PT interconnectors','7 boundaries from frozen network; REE 2012 contextual map','Historical opening/maintenance not available','9 circuit equivalent counts at 7 boundary buses fixed','No operator outage history; 132/66/15 kV ties outside selected boundary equivalent'],
['PDIRD-E 2020 Annex B','July 2020; north circuits PDF93–95','Planning inventory, not case-time telemetry','Lengths/conductors/ampacity transferred where matched','Static parameter evidence; no inferred daily service state'],
['PDIRT 2025–2034 Annex12','December 2024 proposal; PDF323–324','Reference season/regime, not synchronized observations','PDIRT weights applied to contemporaneous national residual','Mapped weights spatial proxy; 18 unmapped delivery references not allocated'],
['DGEG/OSM generation/storage','Frozen generator CSV','366 known date values; 824 missing','Known dates compared with each timestamp; unknown treated available','Retain flags; BESS June 1 within-month proxy; names/OSM tags alone not verified commissioning'],
]
pd.DataFrame(av,columns=['source','source_version','effective_date_basis','in_service_rule','unknown_treatment']).to_csv(OUT/'source_availability_matrix.csv',index=False)
