from pathlib import Path
import pandas as pd,numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
ROOT=Path(__file__).resolve().parents[3];D=ROOT/'paper/revision_v3';F=D/'figures';F.mkdir(exist_ok=True)
plt.rcParams.update({'font.family':'DejaVu Sans','font.size':9,'axes.spines.top':False,'axes.spines.right':False,'pdf.fonttype':42,'svg.fonttype':'none','savefig.bbox':'tight'})
def save(fig,name):
 for ext in ['pdf','svg','png']:fig.savefig(F/(name+'.'+ext),dpi=350 if ext=='png' else None)
 plt.close(fig)
l=pd.read_csv(D/'proxy_monthly_summary.csv');g=pd.read_csv(D/'generation_proxy_monthly_by_energy.csv');r=pd.read_csv(D/'load_proxy_regional_shares.csv');r=r[~r.receiving_area_or_bus.str.startswith('BUS:')&r.receiving_area_or_bus.ne('UNKNOWN')]
fig,axs=plt.subplots(3,1,figsize=(7.2,8.5),layout='constrained');x=np.arange(len(l));axs[0].bar(x,100*l.direct_share_of_consumption,color='#4477AA',label='Observed E-REDES load');axs[0].bar(x,100*l.pdirt_share_of_consumption,bottom=100*l.direct_share_of_consumption,color='#EEAA33',label='PDIRT-allocated residual');axs[0].set_ylim(0,110);axs[0].set_ylabel('Share of consumption (%)');axs[0].set_xticks(x,l.month,rotation=40,ha='right');axs[0].legend(ncol=2,fontsize=8);axs[0].set_title('(a) Monthly energy-weighted load provenance',loc='left',weight='bold')
z=g[g.energy.isin(['Battery Injection','Other Thermal'])].pivot(index='energy',columns='month',values='energy_weighted_proxy_share')*100;im=axs[1].imshow(z,aspect='auto',cmap='YlOrBr',vmin=0,vmax=max(30,float(z.max().max())));axs[1].set_yticks(range(len(z)),z.index);axs[1].set_xticks(range(len(z.columns)),z.columns,rotation=40,ha='right');axs[1].set_title('(b) National proxy share within each energy type (%)',loc='left',weight='bold')
for i in range(len(z)):
 for j in range(len(z.columns)):axs[1].text(j,i,f'{z.iloc[i,j]:.1f}',ha='center',va='center',fontsize=8,color='black' if z.iloc[i,j]<25 else 'white')
fig.colorbar(im,ax=axs[1],shrink=.8)
for region,a in r.groupby('receiving_area_or_bus'):axs[2].plot(a.month,100*a.pdirt_share_of_consumption,marker='o',ms=3,label=region.replace('_',' '))
axs[2].set_ylabel('Residual load share (%)');axs[2].tick_params(axis='x',rotation=40);axs[2].set_ylim(0,55);axs[2].axhline(50,ls='--',color='.5',lw=.8);axs[2].legend(fontsize=7);axs[2].set_title('(c) Model receiving areas (latitude bands, not administrative units)',loc='left',weight='bold');save(fig,'figR1_proxy_provenance')
a=pd.read_csv(D/'operational_ablations/summary.csv');a=a[~a.variant.isin(['BASELINE','FIXED_NEUTRAL_TAPS','RATIO_TAP_FIXED_NEUTRAL'])];fig,ax=plt.subplots(1,2,figsize=(8,4.2),layout='constrained');labels={'Q_HALF':'Q limits ×0.5','Q_150_PERCENT':'Q limits ×1.5','PV_099':'PV = 0.99 p.u.','PV_101':'PV = 1.01 p.u.','NO_LOAD_COMPENSATION':'No load compensation','NO_REACTORS':'No reactors','NO_COMPENSATION_FIXED_TAPS':'No shunts; fixed taps','RATIO_TAP_CONTROL':'Effective ratio taps'};y=np.arange(len(a));ax[0].barh(y,a.max_abs_delta_vm_pu_min,color='#4477AA');ax[0].set_yticks(y,[labels.get(k,k) for k in a.variant]);ax[0].set_xlabel('Max |Δ minimum voltage| (p.u.)');ax[0].set_title('(a) Operational proxies: 22 states',loc='left');ax[1].barh(y,a.max_abs_delta_maximum_line_loading_percent,color='#CC6677');ax[1].set_yticks(y,[]);ax[1].set_xlabel('Max |Δ highest line loading| (pp)');ax[1].set_title('(b) Paired changes from archived baseline',loc='left');save(fig,'figR2_operational_ablations')
h=pd.read_csv(D/'top20_frequency_all_lines.csv').sort_values(['persistent_states','total_selections'],ascending=False).head(20);f=pd.read_csv(D/'top20_frequency_by_state.csv');z=f.pivot(index='line_id',columns='case_id',values='frequency').reindex(h.line_id).fillna(0);fig,ax=plt.subplots(figsize=(8,5.3),layout='constrained');im=ax.imshow(z,aspect='auto',vmin=0,vmax=1,cmap='Blues');ax.set_yticks(range(len(z)),z.index);ax.set_xticks(range(len(z.columns)),[s.replace('PT60_VAL_','')[:8] for s in z.columns],rotation=90,fontsize=7);ax.set_xlabel('Fixed operating timestamp (local date; two selected states per month)');ax.set_title('Top-20 selection frequency across 12 assumptions within each state',loc='left');fig.colorbar(im,ax=ax,label='Selection frequency');save(fig,'figR3_hotspot_persistence')
